[package]
name = "trie"
version = "0.1.0"
authors = ["jeremy beuvry <jeremy.beuvry@epita.fr>"]
edition = "2018"

[dependencies]

[lib]
name = "trie"
path = "src/lib.rs"

[[bin]]
name = "trie"
path = "src/bin/main.rs"

[[bin]]
name = "TextMiningCompiler"
path = "src/bin/compiler.rs"